language: node_js
sudo: false
node_js:
  - 0.12

env:
  global:
  - SAUCE_USERNAME=frypan-knockout-grid
  - secure: MVX+0mZdxEh423FOznHLWsgyVccnF60SdL/2NrZjpkugAPMibf8ljeNoUaL2IntD2GjM3SlchixPZ2SpPh5DMeQJf2WnIXRk/k2/ZqwcIAmGLRxwsxnrnx02HiJ2gZmf95r8TKGliQVppI75OLv3ayzDdpIj9eMS/z+OsAEMpxi8CVITwboSoKKRtjRXGZkiQWHBZTNIsjGhgJU+PNaJfhDpCCbyHdenbJMm8sxp0vmoHXecKefwBUApHmoqyyJRK6uNdodTaHZSOQNbqvJNLSeyTwgemD6424FNeC+xTfYsQsTnlNeU/yP1JWtvJyiiA7UZTUKtB+eKs7JJ3EjTglhb0PCDNLZwakHqIcdofPxVnkjoW4aGy9dKzw9CkrOwgPWYd1JcT71D2vYR0A6LJLQa7q6Z7nABgw4gHkqn+2BedzOexOKG8Vu+2I4+1LfI6Wzz/EDiFgnhDgeyyNowbEkRo7f/vy8Xfz8OqeCKYKDfiHsSlcnMNFJwg7QLr3v4VIjY9C7v9P8uJod5NxPeBMJNtYrO6e39QJ4YT1L3julrj4T3+WJUZCwBNceogCWnNYxwWAbqXoHsazcFrCFVHhgwgCHmHatBkvkm5RZsbln1cyear3nVuq888JTHVH9wgvtEG3ZoB0vL1bRmDimmq8Qh1N7JmQ6u9Z0GEP08O6Y=

script: npm test
